import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import tseslint from "typescript-eslint";

export default tseslint.config(
  // bindings.ts is generated by tauri-specta.
  { ignores: ["dist", "node_modules", "test-results", "playwright-report", "src/bindings.ts"] },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: { ecmaVersion: 2022, globals: { ...globals.browser, ...globals.node } },
    plugins: { "react-hooks": reactHooks },
    rules: {
      ...reactHooks.configs.recommended.rules,
      // No React Compiler here; TanStack Virtual's API is fine without memoization.
      "react-hooks/incompatible-library": "off",
      // Compiler-only checks: a video element held in a ref is changed on purpose.
      "react-hooks/immutability": "off",
      "react-hooks/preserve-manual-memoization": "off",
      "@typescript-eslint/no-unused-vars": ["error", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
    },
  },
  // Playwright fixtures call `use`, which is not React's hook.
  { files: ["e2e/**"], rules: { "react-hooks/rules-of-hooks": "off" } },
);
