// Generated by tauri-specta from src-tauri/src/api (quadcam_lib::specta_builder).
// Do not edit. Regenerate: QUADCAM_UPDATE_BINDINGS=1 cargo test --test bindings

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  Whether the GUI runs, the tools, the effective settings, and the session in brief. */
	status: () => typedError<Status_Serialize, string>(__TAURI_INVOKE("status")),
	/**  Mounted volumes: DVR cards and radio log sources. */
	volumes: () => typedError<Volume[], string>(__TAURI_INVOKE("volumes")),
	/**  The import session, if one is loaded. */
	session: () => typedError<{
	version: number,
	/**  Card mount point or folder the clips came from. */
	source: string,
	/**  The video system of the clips. */
	kind: SourceKind,
	/**  The card the clips were read from; None for a plain folder (no format step). */
	card: CardIdentity | null,
	card_volume: Volume | null,
	staging: string,
	clips: Clip[],
	plans: ClipPlan_Serialize[],
	results: ClipResult[],
	analysed: boolean,
	log_dir: string | null,
	log_day: string | null,
	log_days: string[],
	warnings: string[],
	date_warnings: string[],
	/**  Clip ids whose outputs were added to Photos. */
	in_photos: number[],
	/**  Output folder of the last import. */
	output_dir: string | null,
	/**
	 *  Whether this run joins recordings the DVR split into files. None follows the
	 *  `join_split_recordings` setting.
	 */
	join: boolean | null,
} | null, string>(__TAURI_INVOKE("session")),
	/**  Forgets the session and deletes the session file. */
	clear: () => typedError<Cleared, string>(__TAURI_INVOKE("clear")),
	/**  Copies the clips off a card or folder; a new session. */
	stage: (params: SourceParams) => typedError<Session_Serialize, string>(__TAURI_INVOKE("stage", { params })),
	/**  Probes, recovers and thumbnails the staged clips. */
	analyse: () => typedError<Session_Serialize, string>(__TAURI_INVOKE("analyse")),
	/**  Stage, analyse and date in one go. */
	load: (params: SourceParams) => typedError<Session_Serialize, string>(__TAURI_INVOKE("load", { params })),
	/**  Dates the clips from radio logs. */
	dates: (params: DatesParams) => typedError<Session_Serialize, string>(__TAURI_INVOKE("dates", { params })),
	/**  Changes clip plans (an agent's suggestions unless `editor` is `user`). */
	suggest: (params: SuggestParams) => typedError<Session_Serialize, string>(__TAURI_INVOKE("suggest", { params })),
	/**  Converts and verifies the clips, and optionally adds them to Photos. */
	import: (params: ImportOptions) => typedError<ImportOutcome, string>(__TAURI_INVOKE("import", { params })),
	/**  Adds verified outputs to Photos. */
	photos: (params: PhotosParams) => typedError<ShareReport, string>(__TAURI_INVOKE("photos", { params })),
	/**  Checks verified outputs again. */
	verify: (params: VerifyParams) => typedError<VerifyReport[], string>(__TAURI_INVOKE("verify", { params })),
	/**  Ejects a card. */
	eject: (params: EjectParams) => typedError<Ejected, string>(__TAURI_INVOKE("eject", { params })),
	/**  Runs every format guard and names the card that would be erased. */
	formatPlan: (params: LabelParams) => typedError<FormatPlan, string>(__TAURI_INVOKE("format_plan", { params })),
	/**  Erases the card. With the GUI running, the person must click Erase too. */
	format: (params: FormatRequest) => typedError<FormatPlan, string>(__TAURI_INVOKE("format", { params })),
	/**  The library, narrowed by a filter. */
	library: (params: Filter) => typedError<LibraryView_Serialize, string>(__TAURI_INVOKE("library", { params })),
	/**  Makes the index again from the files. */
	libraryRebuild: () => typedError<RebuildReport, string>(__TAURI_INVOKE("library_rebuild")),
	/**  Sets stars and flags. */
	libraryRate: (params: RateParams) => typedError<LibClip_Serialize[], string>(__TAURI_INVOKE("library_rate", { params })),
	/**  Changes one clip's details, date or time. */
	libraryEdit: (params: LibraryEditParams) => typedError<LibClip_Serialize, string>(__TAURI_INVOKE("library_edit", { params })),
	/**  Changes stars, flag, name and details of clips in one call; checks everything first. */
	libraryUpdate: (params: LibraryUpdateParams) => typedError<LibClip_Serialize[], string>(__TAURI_INVOKE("library_update", { params })),
	/**  Renames a clip, its cuts and its original. */
	libraryRename: (params: RenameParams) => typedError<LibClip_Serialize, string>(__TAURI_INVOKE("library_rename", { params })),
	/**  Sets a clip's cut list. */
	libraryCuts: (params: LibraryCutsParams) => typedError<CutChange, string>(__TAURI_INVOKE("library_cuts", { params })),
	/**  Writes a clip's unsaved cuts as files. */
	libraryExportCuts: (params: ClipIdParams) => typedError<LibCut[], string>(__TAURI_INVOKE("library_export_cuts", { params })),
	/**  Moves clips, with their cuts and originals, to the Trash. */
	libraryTrash: (params: IdsParams) => typedError<TrashReport, string>(__TAURI_INVOKE("library_trash", { params })),
	/**  Puts trashed clips back. */
	libraryUntrash: (params: UntrashParams) => typedError<string[], string>(__TAURI_INVOKE("library_untrash", { params })),
	/**  Adds clips and their cuts to Photos. */
	libraryPhotos: (params: LibraryPhotosParams) => typedError<ShareReport, string>(__TAURI_INVOKE("library_photos", { params })),
	/**  Renames clips to the file-name date format (every clip when `ids` is empty). */
	libraryApplyNameFormat: (params: IdsParams) => typedError<RenameReport, string>(__TAURI_INVOKE("library_apply_name_format", { params })),
	/**
	 *  Matches radio logs to library clips by shape; writes flight numbers and moments only
	 *  with `apply`.
	 */
	libraryMatchLogs: (params: LibMatchParams) => typedError<LibMatchReport_Serialize, string>(__TAURI_INVOKE("library_match_logs", { params })),
	/**  Finds dead air again in a clip. */
	libraryRescan: (params: ClipIdParams) => typedError<LibClip_Serialize, string>(__TAURI_INVOKE("library_rescan", { params })),
	/**  A file the web view can play. */
	libraryPreview: (params: ClipIdParams) => typedError<string, string>(__TAURI_INVOKE("library_preview", { params })),
	/**  Makes missing hover-scrub strips (for every clip when `ids` is empty). */
	libraryStrips: (params: IdsParams) => typedError<number, string>(__TAURI_INVOKE("library_strips", { params })),
	/**  Clips on a card and how many are new to the library. */
	cardStatus: (params: MountParams) => typedError<CardStatus, string>(__TAURI_INVOKE("card_status", { params })),
	/**  The settings file and the effective settings. */
	settings: () => typedError<SettingsView_Serialize, string>(__TAURI_INVOKE("settings")),
	/**  Changes settings. */
	settingsSet: (params: SetSettingsParams) => typedError<SettingsView_Serialize, string>(__TAURI_INVOKE("settings_set", { params })),
	/**  Saved places. */
	places: () => typedError<Place[], string>(__TAURI_INVOKE("places")),
	/**  Searches for an address or a named place. */
	placeSearch: (params: SearchParams) => typedError<GeoResult[], string>(__TAURI_INVOKE("place_search", { params })),
	/**  Creates or changes a saved place. */
	placeSave: (params: PlaceSaveParams) => typedError<Place, string>(__TAURI_INVOKE("place_save", { params })),
	/**  Deletes a saved place. */
	placeDelete: (params: NameParams) => typedError<PlaceRemoved, string>(__TAURI_INVOKE("place_delete", { params })),
	/**  Aircraft profiles and the default. */
	profiles: () => typedError<ProfilesView, string>(__TAURI_INVOKE("profiles")),
	/**  Creates or changes an aircraft profile. */
	profileSave: (params: ProfileSaveParams) => typedError<Profile, string>(__TAURI_INVOKE("profile_save", { params })),
	/**  Deletes an aircraft profile. */
	profileDelete: (params: NameParams) => typedError<Profile, string>(__TAURI_INVOKE("profile_delete", { params })),
	/**  Sets the default profile; an empty name means none. */
	profileDefault: (params: NameParams) => typedError<string | null, string>(__TAURI_INVOKE("profile_default", { params })),
	/**  Sets a session clip's cut list. */
	sessionCuts: (params: SessionCutsParams) => typedError<CutChange, string>(__TAURI_INVOKE("session_cuts", { params })),
	/**  Adds one cut per radio-log pack to a session clip's cut list. */
	sessionSplit: (params: SessionClipParams) => typedError<CutChange, string>(__TAURI_INVOKE("session_split", { params })),
	/**  Adds one cut per radio-log pack to a library clip's cut list (unsaved until exported). */
	librarySplit: (params: ClipIdParams) => typedError<CutChange, string>(__TAURI_INVOKE("library_split", { params })),
	envCheck: () => __TAURI_INVOKE<EnvCheck>("env_check"),
	/**  The output folder used until the user picks one: ~/Movies/quadcam. */
	defaultOutputDir: () => __TAURI_INVOKE<string | null>("default_output_dir"),
	/**  A folder or clip files dropped on the window. */
	loadDropped: (paths: string[]) => typedError<Session_Serialize, string>(__TAURI_INVOKE("load_dropped", { paths })),
	/**  Makes (or reuses) a small H.264 preview of a clip. */
	preview: (id: number) => typedError<string, string>(__TAURI_INVOKE("preview", { id })),
	/**  The GUI's own Erase button: the click in its confirm dialog is the confirmation. */
	formatCard: (label: string) => typedError<FormatPlan, string>(__TAURI_INVOKE("format_card", { label })),
	/**  The person's answer to an agent's format request. */
	answerFormatRequest: (id: number, approve: boolean) => __TAURI_INVOKE<void>("answer_format_request", { id, approve }),
	/**  Lets the webview load files from the library folder (thumbnails and MP4 playback). */
	libraryScope: () => typedError<null, string>(__TAURI_INVOKE("library_scope")),
	/**
	 *  The webview's view of which items apply now: `enabled` and `checked`, by item id, and
	 *  the album item's label (`None` hides it).
	 */
	menuState: (enabled: { [key in string]: boolean }, checked: { [key in string]: boolean }, albumItem: string | null) => __TAURI_INVOKE<void>("menu_state", { enabled, checked, albumItem }),
	/**
	 *  Shows the Share menu for `paths`, next to the rectangle `x`, `y`, `w`, `h` (CSS pixels,
	 *  from the top left of the window's content).
	 */
	share: (paths: string[], x: number | null, y: number | null, w: number | null, h: number | null) => typedError<null, string>(__TAURI_INVOKE("share", { paths, x, y, w, h })),
};

/** Events */
export const events = {
	agentFormatClosed: makeEvent<AgentFormatClosed>("agent-format-closed"),
	agentFormatRequest: makeEvent<AgentFormatRequest>("agent-format-request"),
	importProgress: makeEvent<ImportProgress>("import-progress"),
	importResult: makeEvent<ImportResult>("import-result"),
	libraryChanged: makeEvent<LibraryChanged>("library-changed"),
	libraryTask: makeEvent<LibraryTask>("library-task"),
	menu: makeEvent<Menu>("menu"),
	progress: makeEvent<Progress>("progress"),
	sessionChanged: makeEvent<SessionChanged>("session-changed"),
	settingsChanged: makeEvent<SettingsChanged>("settings-changed"),
	volumesChanged: makeEvent<VolumesChanged>("volumes-changed"),
};

/* Types */
/**  The agent's format request with this id is closed (answered or timed out). */
export type AgentFormatClosed = number;

/**  An agent asked to erase the card. Answer with `answer_format_request`. */
export type AgentFormatRequest = {
	id: number,
	plan: FormatPlan,
};

export type Badge = "matched" | "likely" | "unmatched";

/**  The card the clips were read from, recorded at stage time. */
export type CardIdentity = {
	device_identifier: string,
	whole_disk: string,
	volume_uuid: string | null,
	volume_name: string | null,
	total_size: number,
	media_name: string | null,
};

export type CardStatus = {
	mount: string,
	clips: number,
	/**  Clips whose content is not in the library yet. */
	new: number,
	free: number | null,
	size: number,
};

/**  `clear`'s answer. */
export type Cleared = {
	cleared: boolean,
};

export type Clip = {
	id: number,
	name: string,
	rel: string,
	card_path: string,
	size: number,
	staged: string | null,
	/**  Set when the copy failed, for example because the card was pulled. */
	stage_error: string | null,
	status: ClipStatus,
	/**  Duration of what will be converted (the recovered length for a half-written clip). */
	duration: number | null,
	/**  A rewritten copy of a half-written clip; it becomes the conversion source. */
	recovered: string | null,
	probe: Probe | null,
	thumb: string | null,
	/**  One line on what analysis found. */
	detail: string,
	/**  Dead air found in the clip's frames, and the ranges worth keeping. */
	signal?: SignalScan | null,
	/**
	 *  Content fingerprint (see `fingerprint`). Names the clip's cached thumbnail and
	 *  preview, since DVRs reuse file names: the Echo restarts at PICT0001 after a format.
	 */
	key?: string,
	/**  The video system the clip came from. */
	kind?: SourceKind,
	/**  The time the clip itself recorded (DJI: the unit's clock), read at analysis. */
	clock?: string | null,
	/**
	 *  Staged copies of files that belong to the clip (a DJI `.SRT`). They are kept next
	 *  to the original.
	 */
	sidecars?: string[],
	/**  The card file's modified time, when it has one. */
	mtime?: string | null,
	/**  Set on the first file of a recording the DVR split into several files (see `join`). */
	join?: Join | null,
	/**
	 *  Set on a later file of a joined recording: the id of the clip it is part of. It
	 *  imports as part of that clip, not on its own.
	 */
	part_of?: number | null,
};

export type ClipDeletion = {
	id: number,
	/**  The clip's file on the card or folder. */
	path: string,
	state: DeletionState,
	/**  Why the file stays. None when it was deleted. */
	reason: string | null,
};

/**  One library clip, by id. */
export type ClipIdParams = {
	id: string,
};

/**  What the person (or an agent) set on one clip. Missing values come from the profile. */
export type ClipMeta = {
	/**  Profile name. None: the log's model, then the session default. */
	profile?: string | null,
	location?: Location | null,
	/**  Keywords on top of the profile's. */
	keywords?: string[],
	/**  Overrides the profile's author. */
	author?: string | null,
};

/**
 *  What will happen to one clip on import. The GUI shows it and edits it; an agent may
 *  suggest values for it.
 */
export type ClipPlan = ClipPlan_Serialize | ClipPlan_Deserialize;

/**
 *  What will happen to one clip on import. The GUI shows it and edits it; an agent may
 *  suggest values for it.
 */
export type ClipPlan_Deserialize = {
	id: number,
	skip: boolean,
	date: string,
	/**  The time of day: from the radio log, or set by hand. None means local noon. */
	time: string | null,
	source: DateSource,
	badge: Badge,
	segments: number,
	name: string,
	note: string,
	suggested?: Suggested,
	/**  Why the agent suggested what it did, shown next to the suggestion. */
	reason?: string | null,
	/**  Moments from the radio log, in clip seconds (log time plus `log_offset_s`). */
	moments?: Moment[],
	/**  Median seconds between the log rows the clip claimed. 0.5 s logs give rough moments. */
	log_interval_s?: number | null,
	/**
	 *  Seconds into the clip where the first armed log row falls. 0 assumes the clip starts
	 *  at arm; the DVR usually starts earlier, so the person can set it.
	 */
	log_offset_s?: number | null,
	/**  Ranges to export as extra files (`<name>_cutN`), in clip seconds. */
	cuts?: Span[],
	/**  Location, profile, keywords and author for this clip. */
	meta?: ClipMeta,
	/**  The EdgeTX model of the matched log; it picks the profile when the clip has none. */
	log_model?: string | null,
	flight?: FlightStats_Deserialize | null,
	/**  Why the radio log matched, or how sure the match is. */
	match_reason?: string | null,
};

/**
 *  What will happen to one clip on import. The GUI shows it and edits it; an agent may
 *  suggest values for it.
 */
export type ClipPlan_Serialize = {
	id: number,
	skip: boolean,
	date: string,
	/**  The time of day: from the radio log, or set by hand. None means local noon. */
	time: string | null,
	source: DateSource,
	badge: Badge,
	segments: number,
	name: string,
	note: string,
	suggested: Suggested,
	/**  Why the agent suggested what it did, shown next to the suggestion. */
	reason: string | null,
	/**  Moments from the radio log, in clip seconds (log time plus `log_offset_s`). */
	moments: Moment[],
	/**  Median seconds between the log rows the clip claimed. 0.5 s logs give rough moments. */
	log_interval_s: number | null,
	/**
	 *  Seconds into the clip where the first armed log row falls. 0 assumes the clip starts
	 *  at arm; the DVR usually starts earlier, so the person can set it.
	 */
	log_offset_s: number | null,
	/**  Ranges to export as extra files (`<name>_cutN`), in clip seconds. */
	cuts: Span[],
	/**  Location, profile, keywords and author for this clip. */
	meta: ClipMeta,
	/**  The EdgeTX model of the matched log; it picks the profile when the clip has none. */
	log_model: string | null,
	flight: FlightStats_Serialize | null,
	/**  Why the radio log matched, or how sure the match is. */
	match_reason: string | null,
};

export type ClipResult = {
	id: number,
	outcome: Outcome,
	output: string | null,
	original: string | null,
	size: number,
	error: string | null,
	/**  How the file was made: the encoder that ran, or `copy` or `remux`. */
	encoder: Encoded | null,
	/**  The metadata written, so a later verify checks exactly what went into the file. */
	meta?: Meta | null,
	/**  One extra output per cut range of the clip. */
	cuts?: CutResult[],
	/**  The QuickTime items written (see `qtmeta`), so a later verify checks them too. */
	qt?: ([string, string])[],
};

export type ClipStatus = "ok" | "incomplete" | "empty";

/**  The answer to a cut change. */
export type CutChange = 
/**  The new list is saved. `kept` and `trashed` list the files of removed cuts. */
{ status: "applied"; cuts: Span[]; kept?: string[]; trashed?: string[] } | 
/**
 *  Nothing changed: these exported files would lose their cut. Ask, then call again
 *  with a `RemovedCuts` decision.
 */
{ status: "confirm"; files: string[] };

/**  One cut range written as its own file next to the clip's output. */
export type CutResult = {
	start: number | null,
	end: number | null,
	outcome: Outcome,
	output: string | null,
	size: number,
	error: string | null,
};

/**  How the date starts a file name. */
export type DateFormat = 
/**  `2026-09-25` */
"YYYY-MM-DD" | 
/**  `26.09.25` */
"YY.MM.DD";

export type DateSource = "log" | "import" | "edited" | 
/**  The clip's own clock (DJI). */
"clip";

/**  `dates`: where the radio logs come from, and the log day to match. */
export type DatesParams = {
	logs?: LogChoice,
	day: string | null,
};

/**  Settings every surface starts from. The GUI keeps them in sync with its settings store. */
export type Defaults = Defaults_Serialize | Defaults_Deserialize;

/**  Settings every surface starts from. The GUI keeps them in sync with its settings store. */
export type Defaults_Deserialize = {
	output_dir: string | null,
	format: Format,
	encoder: Encoder,
	keep_originals: boolean,
	add_time: boolean,
	/**
	 *  After an import, delete the clip files that verified from the card or folder they
	 *  came from. Every other file stays. Off by default; an import may turn it off for
	 *  one run, never on.
	 */
	delete_clips_after_import?: boolean,
	/**
	 *  Import a recording the DVR split into several files as one clip (see `join`). On by
	 *  default; a run or a clip may keep the files separate.
	 */
	join_split_recordings?: boolean,
	default_name: string,
	photos_album: string,
	log_dir: string | null,
	tunables: Tunables,
	/**  FAT32 volume name for the format step. */
	format_label?: string,
	places?: Place[],
	profiles?: Profile[],
	default_profile?: string | null,
	/**  How imports are filed in the library folder (`output_dir`). */
	layout?: Layout,
	/**  Add the place name to day folders. */
	place_folders?: boolean,
	/**  Place search provider: `apple` or `nominatim`. */
	geocoder?: string,
	/**  How the date starts file names. */
	name_date_format?: DateFormat,
	/**  Google Places API key from the settings file. Never serialized. */
	google_places_key?: string | null,
};

/**  Settings every surface starts from. The GUI keeps them in sync with its settings store. */
export type Defaults_Serialize = {
	output_dir: string | null,
	format: Format,
	encoder: Encoder,
	keep_originals: boolean,
	add_time: boolean,
	/**
	 *  After an import, delete the clip files that verified from the card or folder they
	 *  came from. Every other file stays. Off by default; an import may turn it off for
	 *  one run, never on.
	 */
	delete_clips_after_import: boolean,
	/**
	 *  Import a recording the DVR split into several files as one clip (see `join`). On by
	 *  default; a run or a clip may keep the files separate.
	 */
	join_split_recordings: boolean,
	default_name: string,
	photos_album: string,
	log_dir: string | null,
	tunables: Tunables,
	/**  FAT32 volume name for the format step. */
	format_label: string,
	places: Place[],
	profiles: Profile[],
	default_profile: string | null,
	/**  How imports are filed in the library folder (`output_dir`). */
	layout: Layout,
	/**  Add the place name to day folders. */
	place_folders: boolean,
	/**  Place search provider: `apple` or `nominatim`. */
	geocoder: string,
	/**  How the date starts file names. */
	name_date_format: DateFormat,
};

/**  What happened to one clip's file on the card or folder after an import. */
export type DeletionState = 
/**  The file was deleted. */
"deleted" | 
/**  The file stays; `reason` says why. */
"kept";

export type DiskInfo = {
	device_identifier: string,
	parent_whole_disk: string,
	internal: boolean,
	removable: boolean,
	ejectable: boolean,
	total_size: number,
	volume_uuid: string | null,
	volume_name: string | null,
	mount_point: string | null,
	/**  `FilesystemPersonality`, or `FilesystemName` where FSKit leaves the former empty. */
	filesystem: string | null,
	media_name: string | null,
	bus_protocol: string | null,
};

export type Editor = "user" | "agent";

/**  `eject`: a mount point or `/dev/diskN`; None ejects the session's card. */
export type EjectParams = {
	target: string | null,
};

/**  `eject`'s answer. */
export type Ejected = {
	ejected: boolean,
};

/**  How an import made its file: the encoder that ran, or a copy of the source's frames. */
export type Encoded = "videotoolbox" | "x264" | 
/**  The source file byte for byte (`EncodePlan::Copy`). */
"copy" | 
/**  ffmpeg copied the frames into a new container (`EncodePlan::Remux`). */
"remux";

export type Encoder = 
/**  `h264_videotoolbox -q:v 65`, falling back to x264 on failure. */
"videotoolbox" | 
/**  `libx264 -preset veryfast -crf 20` (software fallback). */
"x264";

export type EnvCheck = {
	tools: Tools | null,
	error: string | null,
	install_hint: string,
	socket: string | null,
};

/**  The smart groups and other ways to narrow the library. */
export type Filter = {
	/**  Words that must all appear in the name, note, place, aircraft, keywords or DVR name. */
	query?: string | null,
	/**  `all`, `last_import`, `moments`, `picks`, `rejected`, `not_in_photos`. */
	group?: string | null,
	day?: string | null,
	place?: string | null,
	aircraft?: string | null,
	min_rating?: number | null,
};

export type Flag = "none" | "pick" | "reject";

/**  Flight numbers from the radio log rows a clip claimed. */
export type FlightStats = FlightStats_Serialize | FlightStats_Deserialize;

/**  Flight numbers from the radio log rows a clip claimed. */
export type FlightStats_Deserialize = {
	armed_s: number | null,
	packs: number,
	min_rx_bat_v: number | null,
	min_lq: number | null,
	min_rssi_db: number | null,
	max_throttle: number | null,
	/**
	 *  Each pack's armed range, in clip seconds (log time plus the log offset), in order.
	 *  Empty in files from before QuadCam 0.6.3; a library re-match writes it.
	 */
	pack_spans?: Span[],
};

/**  Flight numbers from the radio log rows a clip claimed. */
export type FlightStats_Serialize = {
	armed_s: number | null,
	packs: number,
	min_rx_bat_v: number | null,
	min_lq: number | null,
	min_rssi_db: number | null,
	max_throttle: number | null,
	/**
	 *  Each pack's armed range, in clip seconds (log time plus the log offset), in order.
	 *  Empty in files from before QuadCam 0.6.3; a library re-match writes it.
	 */
	pack_spans?: Span[],
};

export type Format = "mp4" | "mov";

export type FormatPlan = {
	/**  Whole disk, for example `disk4`. */
	disk: string,
	device: string,
	volume_uuid: string,
	volume_name: string,
	size: number,
	media_name: string,
	clip_count: number,
	label: string,
};

/**
 *  An explicit format request from the CLI or an agent. Every field must match the card
 *  the clips were read from.
 */
export type FormatRequest = {
	/**  Whole-disk device node, for example `/dev/disk4`. */
	device: string,
	volume_uuid: string,
	label?: string | null,
	/**  Must be true. */
	confirm?: boolean,
};

/**  One search hit. */
export type GeoResult = {
	name: string,
	address: string,
	lat: number | null,
	lon: number | null,
	provider: string,
};

/**
 *  Library clips, by id. For `library_apply_name_format` and `library_strips`, none
 *  means every clip.
 */
export type IdsParams = {
	ids?: string[],
};

/**  Per-run overrides for an import. Anything missing comes from `Defaults`. */
export type ImportOptions = {
	output_dir?: string | null,
	format?: Format | null,
	encoder?: Encoder | null,
	keep_originals?: boolean | null,
	add_time?: boolean | null,
	add_to_photos?: boolean,
	album?: string | null,
	/**
	 *  Keep every clip file on the card or folder this run, even when the
	 *  `delete_clips_after_import` setting is on. Nothing here turns deletion on: the
	 *  setting is the only consent.
	 */
	keep_clips?: boolean,
};

export type ImportOutcome = {
	summary: Summary,
	photos: SerdeResult<ShareReport, string> | null,
	/**
	 *  What "Delete clips after import" did with each clip. None when it did not run: the
	 *  setting is off, or this run kept the clips.
	 */
	clip_deletion?: ClipDeletion[] | null,
};

/**  Converting one clip: `seconds` of `duration` done. */
export type ImportProgress = {
	id: number,
	seconds: number | null,
	duration: number | null,
};

/**  One clip finished converting (verified, failed or skipped). */
export type ImportResult = ClipResult;

/**  A recording the DVR split into files, on its first file's clip. */
export type Join = {
	/**  The later files' clip ids, in recording order. */
	parts: number[],
	/**  The `ffconcat` list of every file, in staging. */
	list: string,
	/**  True while the files import as one clip. */
	on: boolean,
	/**  Bytes of every file's source, for the free-space check. */
	bytes: number,
	swap: Swap,
};

/**  `format_plan`: the FAT32 volume name; None uses the setting. */
export type LabelParams = {
	label: string | null,
};

/**  Where a clip goes inside the library folder. */
export type Layout = 
/**  `YYYY/YYYY-MM-DD/` */
"year_day" | 
/**  `YYYY-MM-DD/` */
"day" | 
/**  Every file in the library folder itself. */
"flat";

/**  One clip in the library. */
export type LibClip = LibClip_Serialize | LibClip_Deserialize;

/**  One clip in the library. */
export type LibClip_Deserialize = {
	id: string,
	/**  Relative to the library folder. */
	path: string,
	/**  The short name; empty when the clip was imported without one. */
	title: string,
	note: string,
	date: string,
	/**  `HH:MM`, when the clip has a time of day (from its radio log or set by hand). */
	time?: string | null,
	duration: number | null,
	size: number,
	rating?: number,
	flag?: Flag,
	place?: string | null,
	location?: Location | null,
	/**  Profile name, else the aircraft written in the file. */
	aircraft?: string | null,
	keywords?: string[],
	author?: string | null,
	/**  Radio-log moments, in clip seconds. */
	moments?: Moment[],
	/**  Ranges with a picture; empty when the clip has no dead air (or was never scanned). */
	keep?: Span[],
	stats?: FlightStats_Deserialize | null,
	cuts?: LibCut[],
	/**  Cut ranges set in the library but not written yet. Only the index holds these. */
	pending_cuts?: Span[],
	in_photos?: boolean,
	/**  The kept DVR original, relative to the library folder. */
	original?: string | null,
	/**  The DVR file name it came from. */
	dvr?: string | null,
	/**  The import it came in with (`YYYYMMDD-HHMMSS`). */
	import?: string | null,
	/**  Set for a cut file kept on its own after its cut was removed: (source id, range). */
	cut_of?: [string, Span] | null,
	/**  Earlier ids of this clip (QuadCam 0.4's). Lookups by them still find it. */
	aliases?: string[],
	/**
	 *  The later DVR files of a split recording joined into this clip. Their fingerprints
	 *  count as imported.
	 */
	parts?: LibPart[],
};

/**  One clip in the library. */
export type LibClip_Serialize = {
	id: string,
	/**  Relative to the library folder. */
	path: string,
	/**  The short name; empty when the clip was imported without one. */
	title: string,
	note: string,
	date: string,
	/**  `HH:MM`, when the clip has a time of day (from its radio log or set by hand). */
	time: string | null,
	duration: number | null,
	size: number,
	rating: number,
	flag: Flag,
	place: string | null,
	location: Location | null,
	/**  Profile name, else the aircraft written in the file. */
	aircraft: string | null,
	keywords: string[],
	author: string | null,
	/**  Radio-log moments, in clip seconds. */
	moments: Moment[],
	/**  Ranges with a picture; empty when the clip has no dead air (or was never scanned). */
	keep: Span[],
	stats: FlightStats_Serialize | null,
	cuts: LibCut[],
	/**  Cut ranges set in the library but not written yet. Only the index holds these. */
	pending_cuts: Span[],
	in_photos: boolean,
	/**  The kept DVR original, relative to the library folder. */
	original: string | null,
	/**  The DVR file name it came from. */
	dvr: string | null,
	/**  The import it came in with (`YYYYMMDD-HHMMSS`). */
	import: string | null,
	/**  Set for a cut file kept on its own after its cut was removed: (source id, range). */
	cut_of: [string, Span] | null,
	/**  Earlier ids of this clip (QuadCam 0.4's). Lookups by them still find it. */
	aliases?: string[],
	/**
	 *  The later DVR files of a split recording joined into this clip. Their fingerprints
	 *  count as imported.
	 */
	parts?: LibPart[],
};

/**  A cut written as its own file next to its clip. */
export type LibCut = {
	/**  Relative to the library folder. */
	path: string,
	start: number | null,
	end: number | null,
	size: number,
};

/**  Details to change on a library clip. Missing fields stay as they are. */
export type LibEdit = {
	note?: string | null,
	keywords?: string[] | null,
	author?: string | null,
	/**  A saved place's name; empty removes the location. */
	place?: string | null,
	location?: Location | null,
	/**  A new flying day. The clip, its cuts and its original move to that day's folder. */
	date?: string | null,
	/**
	 *  Time of day, `HH:MM`; empty means local noon. Without it a new date keeps the
	 *  clip's time.
	 */
	time?: string | null,
	/**  An aircraft profile name; empty removes the profile's details. */
	profile?: string | null,
};

/**  A clip as the front ends see it: the index entry plus absolute paths. */
export type LibItem = LibItem_Serialize | LibItem_Deserialize;

/**  A clip as the front ends see it: the index entry plus absolute paths. */
export type LibItem_Deserialize = {
	name: string,
	file: string,
	/**  The hover-scrub strip, once made. */
	strip: string | null,
	/**  One frame, when no strip could be made. */
	poster: string | null,
	/**  Neither a strip nor a poster could be made. */
	no_picture: boolean,
	last_import: boolean,
} & LibClip_Deserialize;

/**  A clip as the front ends see it: the index entry plus absolute paths. */
export type LibItem_Serialize = {
	name: string,
	file: string,
	/**  The hover-scrub strip, once made. */
	strip: string | null,
	/**  One frame, when no strip could be made. */
	poster: string | null,
	/**  Neither a strip nor a poster could be made. */
	no_picture: boolean,
	last_import: boolean,
} & LibClip_Serialize;

/**  One clip's result. */
export type LibMatch = LibMatch_Serialize | LibMatch_Deserialize;

/**  `library_match_logs`: which clips, which logs, and whether to write the result. */
export type LibMatchParams = {
	/**  Library clip ids; empty means every clip (cuts excluded). */
	ids?: string[],
	/**  The log folder; the `logDir` setting when missing. */
	logs?: string | null,
	/**
	 *  One log day for every clip. Without it, each clip is matched to the logs of its own
	 *  day, and clips with none to the newest reset-clock day (`2000-01-01`).
	 */
	day?: string | null,
	/**
	 *  Write the flight numbers and moments into the matched clips' files. Without it,
	 *  nothing changes. Writes "matched" clips, and "likely" ones only when named in `ids`.
	 */
	apply?: boolean,
};

export type LibMatchReport = LibMatchReport_Serialize | LibMatchReport_Deserialize;

export type LibMatchReport_Deserialize = {
	clips: LibMatch_Deserialize[],
	warnings: string[],
};

export type LibMatchReport_Serialize = {
	clips: LibMatch_Serialize[],
	warnings: string[],
};

/**  One clip's result. */
export type LibMatch_Deserialize = {
	id: string,
	path: string,
	duration: number | null,
	badge: Badge,
	/**  The log day matched against. */
	log_day: string | null,
	/**  The log's start date and time, when the radio clock is believable. */
	log_date: string | null,
	log_time: string | null,
	log_model: string | null,
	packs: number,
	reason: string | null,
	/**
	 *  The clip second of the first armed row, when the clip's picture placed the log.
	 *  `flight.pack_spans` are in clip seconds with it.
	 */
	log_offset_s: number | null,
	flight: FlightStats_Deserialize | null,
	moments: number,
	/**  The flight numbers and moments were written into the file. */
	applied: boolean,
};

/**  One clip's result. */
export type LibMatch_Serialize = {
	id: string,
	path: string,
	duration: number | null,
	badge: Badge,
	/**  The log day matched against. */
	log_day: string | null,
	/**  The log's start date and time, when the radio clock is believable. */
	log_date: string | null,
	log_time: string | null,
	log_model: string | null,
	packs: number,
	reason: string | null,
	/**
	 *  The clip second of the first armed row, when the clip's picture placed the log.
	 *  `flight.pack_spans` are in clip seconds with it.
	 */
	log_offset_s: number | null,
	flight: FlightStats_Serialize | null,
	moments: number,
	/**  The flight numbers and moments were written into the file. */
	applied: boolean,
};

/**  A later file of a split recording that was joined into a clip. */
export type LibPart = {
	/**  The file's content fingerprint, like a clip id. */
	source: string,
	/**  Its DVR file name. */
	dvr: string,
};

/**
 *  Every change one call may make to library clips: stars and flag, a new name (one clip
 *  only), and the details in `LibEdit`. Missing fields stay as they are.
 */
export type LibUpdate = {
	/**  Stars, 0 to 5; 0 clears. */
	rating?: number | null,
	flag?: Flag | null,
	/**  A new short name; needs exactly one clip. */
	name?: string | null,
} & LibEdit;

/**  The library index changed. Read it again with `library`. */
export type LibraryChanged = null;

/**  `library_cuts`: a clip's new cut list, and what happens to exported cuts it drops. */
export type LibraryCutsParams = {
	id: string,
	cuts?: Span[],
	removed_cuts?: RemovedCuts | null,
};

/**  `library_edit`: one clip's details. Missing fields stay as they are. */
export type LibraryEditParams = {
	id: string,
} & LibEdit;

/**  `library_photos`: the clips to add with their cuts, and the album (None: the setting). */
export type LibraryPhotosParams = {
	ids?: string[],
	album?: string | null,
};

/**  A library job's progress: `done` of `total`. */
export type LibraryTask = {
	task: Task,
	done: number,
	total: number,
};

/**
 *  `library_update`: stars, flag, name and details for these clips, checked before any
 *  file changes.
 */
export type LibraryUpdateParams = {
	ids?: string[],
} & LibUpdate;

export type LibraryView = LibraryView_Serialize | LibraryView_Deserialize;

export type LibraryView_Deserialize = {
	root: string,
	exists: boolean,
	/**  Media files in the folder that the index does not list (an older export to adopt). */
	unindexed: number,
	last_import: string | null,
	totals: Totals,
	groups: { [key in string]: ([string, number])[] },
	layout: Layout,
	place_folders: boolean,
	clips: LibItem_Deserialize[],
};

export type LibraryView_Serialize = {
	root: string,
	exists: boolean,
	/**  Media files in the folder that the index does not list (an older export to adopt). */
	unindexed: number,
	last_import: string | null,
	totals: Totals,
	groups: { [key in string]: ([string, number])[] },
	layout: Layout,
	place_folders: boolean,
	clips: LibItem_Serialize[],
};

/**  A location in decimal degrees. */
export type Location = {
	lat: number | null,
	lon: number | null,
	/**  The saved place it came from, if any. */
	name?: string | null,
};

/**  Where the log folder for date planning comes from. */
export type LogChoice = 
/**  Keep the session's current folder (or the default). */
{ kind: "keep" } | { kind: "none" } | { kind: "dir"; path: string };

/**  A menu item was chosen: its id. */
export type Menu = string;

export type Meta = {
	title: string,
	comment: string,
	creation_time: string,
	date: string,
	description: string,
};

export type Moment = {
	kind: MomentKind,
	/**  Seconds from the start of the clip. */
	start: number | null,
	end: number | null,
	/**  0..1. Coarse logs score lower; see `detail`. */
	score: number | null,
	source: Source,
	/**  One line on what was seen. */
	detail: string,
};

export type MomentKind = 
/**  Full aileron, held. */
"roll" | 
/**  Full elevator, held. */
"flip" | 
/**  Throttle from low to near full, fast. */
"punch" | 
/**  Throttle near zero for a while mid-flight, then a punch. */
"dive" | 
/**  The log segment ends right after big inputs. Low confidence. */
"crash" | 
/**  No usable picture: blue screen, static, test pattern, black. */
"dead_air";

/**  `card_status`: a card's mount point. */
export type MountParams = {
	mount: string,
};

/**  A library file in the Trash: the clip it belongs to, where it was, where it is now. */
export type Moved = {
	id: string,
	from: string,
	to: string,
};

/**  A place or profile, by name. */
export type NameParams = {
	name: string,
};

export type Outcome = "verified" | "failed" | "skipped";

/**  The step `Progress` reports on. */
export type Phase = 
/**  Copying clips off the card. */
"stage" | 
/**  Probing, recovering and thumbnailing them. */
"analyse";

/**  `photos`: the clips to add (all verified clips when None), and the album. */
export type PhotosParams = {
	ids: number[] | null,
	album: string | null,
};

/**  A saved place, kept in the settings file. */
export type Place = {
	name: string,
	lat: number | null,
	lon: number | null,
};

export type PlaceRemoved = {
	name: string,
	/**  Profiles that used it as their default place; they now have none. */
	profiles_cleared: string[],
};

/**  `place_save`: creates a place or changes the one with this name; `new_name` renames it. */
export type PlaceSaveParams = {
	name: string,
	new_name?: string | null,
	lat?: number | null,
	lon?: number | null,
};

/**  A change to one clip's plan. Missing fields stay as they are. */
export type PlanPatch = {
	id: number,
	date?: string | null,
	/**  Time of day, `HH:MM` (or `HH:MM:SS`); empty removes it (local noon). */
	time?: string | null,
	name?: string | null,
	note?: string | null,
	skip?: boolean | null,
	reason?: string | null,
	/**  Replaces the clip's cut list. An empty list removes every cut. */
	cuts?: Span[] | null,
	/**  Where the first armed log row falls in the clip, in seconds. Moves the log moments. */
	log_offset_s?: number | null,
	/**  Aircraft profile name; empty to fall back to the log's model or the default. */
	profile?: string | null,
	/**  Location in decimal degrees. */
	location?: Location | null,
	/**
	 *  A saved place's name (`Core::patch` turns it into `location`); empty removes the
	 *  clip's location.
	 */
	place?: string | null,
	/**  Replaces the clip's own keywords. */
	keywords?: string[] | null,
	/**  Empty falls back to the profile's author. */
	author?: string | null,
	/**
	 *  What happens to the files of exported cuts that `cuts` drops. Required when it
	 *  drops one.
	 */
	removed_cuts?: RemovedCuts | null,
	/**
	 *  True adds one cut per radio-log pack (see `trim::flight_cuts`) to the cut list,
	 *  after `cuts` when both are given.
	 */
	split_by_flight?: boolean | null,
	/**
	 *  For the first file of a recording the DVR split into files: true imports the files
	 *  as one clip, false keeps them as clips of their own.
	 */
	joined?: boolean | null,
};

export type Probe = {
	duration: number | null,
	video_packets: number,
	video_streams: number,
	audio_streams: number,
	fps: number | null,
	width: number | null,
	height: number | null,
	tags: { [key in string]: string },
	/**  Anything ffprobe printed at `-v error`. */
	errors: string,
};

/**
 *  One aircraft setup, kept in the settings file. Every field is optional. A clip dated
 *  from a radio log picks the profile whose `edgetx_models` holds the log's model name;
 *  without one, the first profile whose `video_system` names the clip's source (`DJI`,
 *  `analog`).
 */
export type Profile = {
	name?: string,
	/**  The aircraft, for example "5-inch freestyle". */
	aircraft?: string,
	/**  The recorder: goggles or DVR maker and model. Written as the camera make and model. */
	camera_make?: string,
	camera_model?: string,
	/**
	 *  A label: analog, DJI, Walksnail, HDZero. A clip of that source picks the profile
	 *  when nothing more specific does.
	 */
	video_system?: string,
	keywords?: string[],
	author?: string,
	/**  Name of a saved place used when a clip has no location. */
	place?: string | null,
	/**  EdgeTX model names (the start of the log file name) that mean this profile. */
	edgetx_models?: string[],
};

/**
 *  `profile_save`: creates a profile or changes the given fields of the one with this name;
 *  `new_name` renames it.
 */
export type ProfileSaveParams = {
	name: string,
	new_name?: string | null,
	fields?: { [key in string]: unknown },
};

/**  `profiles`' answer: every profile and the default's name. */
export type ProfilesView = {
	profiles: Profile[],
	default_profile: string | null,
};

/**  Loading a card: clip `index` of `total`, `done` of `size` bytes copied. */
export type Progress = {
	phase: Phase,
	index: number,
	total: number,
	done: number,
	size: number,
};

/**  `library_rate`: stars (0 clears) and a pick or reject flag for these clips. */
export type RateParams = {
	ids?: string[],
	rating?: number | null,
	flag?: Flag | null,
};

export type RebuildReport = {
	clips: number,
	cuts: number,
	problems: string[],
};

/**
 *  What happens to the file of an exported cut that is removed from the list. With no
 *  decision, the change is not applied and the caller is asked.
 */
export type RemovedCuts = 
/**  The file stays; it becomes a clip of its own in the library. */
"keep" | 
/**  The file goes to the Trash. */
"trash";

/**  `library_rename`: a clip's new short name. */
export type RenameParams = {
	id: string,
	name?: string | null,
};

/**  What `library_apply_name_format` did, by path relative to the library folder. */
export type RenameReport = {
	renamed: ([string, string])[],
	unchanged: number,
	/**  Names that do not start with a date. */
	skipped: string[],
	failed: ([string, string])[],
};

/**  `place_search`: an address or a place name, and an optional provider and result limit. */
export type SearchParams = {
	query: string,
	provider?: string | null,
	limit?: number | null,
};

/**
 *  How serde writes a `Result`: `{"Ok": value}` or `{"Err": error}`. Fields of type
 *  `Result` take this as their TypeScript type (specta's own `Result` type has another
 *  shape).
 */
export type SerdeResult<T, E> = ({ Ok: T }) & { Err?: never } | ({ Err: E }) & { Ok?: never };

export type Session = Session_Serialize | Session_Deserialize;

export type SessionBrief = {
	source: string,
	/**  The video system of the clips. */
	kind: SourceKind,
	card: string | null,
	clips: number,
	analysed: boolean,
	imported: number,
	failed: number,
	format_ready: SerdeResult<null, string>,
};

/**  The session changed. Read it again with `session`. */
export type SessionChanged = null;

/**  One session clip. */
export type SessionClipParams = {
	id: number,
};

/**  `session_cuts`: a session clip's new cut list, and what happens to exported cuts it drops. */
export type SessionCutsParams = {
	id: number,
	cuts: Span[],
	removed_cuts?: RemovedCuts | null,
};

export type Session_Deserialize = {
	version: number,
	/**  Card mount point or folder the clips came from. */
	source: string,
	/**  The video system of the clips. */
	kind?: SourceKind,
	/**  The card the clips were read from; None for a plain folder (no format step). */
	card: CardIdentity | null,
	card_volume: Volume | null,
	staging: string,
	clips: Clip[],
	plans: ClipPlan_Deserialize[],
	results: ClipResult[],
	analysed: boolean,
	log_dir: string | null,
	log_day: string | null,
	log_days: string[],
	warnings: string[],
	date_warnings: string[],
	/**  Clip ids whose outputs were added to Photos. */
	in_photos: number[],
	/**  Output folder of the last import. */
	output_dir: string | null,
	/**
	 *  Whether this run joins recordings the DVR split into files. None follows the
	 *  `join_split_recordings` setting.
	 */
	join?: boolean | null,
};

export type Session_Serialize = {
	version: number,
	/**  Card mount point or folder the clips came from. */
	source: string,
	/**  The video system of the clips. */
	kind: SourceKind,
	/**  The card the clips were read from; None for a plain folder (no format step). */
	card: CardIdentity | null,
	card_volume: Volume | null,
	staging: string,
	clips: Clip[],
	plans: ClipPlan_Serialize[],
	results: ClipResult[],
	analysed: boolean,
	log_dir: string | null,
	log_day: string | null,
	log_days: string[],
	warnings: string[],
	date_warnings: string[],
	/**  Clip ids whose outputs were added to Photos. */
	in_photos: number[],
	/**  Output folder of the last import. */
	output_dir: string | null,
	/**
	 *  Whether this run joins recordings the DVR split into files. None follows the
	 *  `join_split_recordings` setting.
	 */
	join: boolean | null,
};

/**  `settings_set`: settings by file key or CLI/MCP name; null resets one. */
export type SetSettingsParams = {
	values: { [key in string]: unknown },
};

/**  The settings file changed. Read it again with `settings`. */
export type SettingsChanged = null;

/**  The settings file: where it is, what it holds, and the defaults that come out of it. */
export type SettingsView = SettingsView_Serialize | SettingsView_Deserialize;

/**  The settings file: where it is, what it holds, and the defaults that come out of it. */
export type SettingsView_Deserialize = {
	path: string,
	/**  The file's values, by file key. Secrets read `"(set)"`. */
	values: { [key in string]: unknown },
	/**  What every surface uses: the values on top of the defaults. */
	effective: Defaults_Deserialize,
};

/**  The settings file: where it is, what it holds, and the defaults that come out of it. */
export type SettingsView_Serialize = {
	path: string,
	/**  The file's values, by file key. Secrets read `"(set)"`. */
	values: { [key in string]: unknown },
	/**  What every surface uses: the values on top of the defaults. */
	effective: Defaults_Serialize,
};

export type ShareReport = {
	added: string[],
	failed: ([string, string])[],
	album: string | null,
};

/**  The result of scanning a clip's frames. */
export type SignalScan = {
	/**  Seconds between sampled frames. */
	step: number | null,
	samples: number,
	dead_air: Moment[],
	/**  Suggested ranges to keep; empty when the clip has no dead air. */
	keep: Span[],
};

/**  Where a moment's evidence came from. */
export type Source = "radio_log" | "video";

/**  Which video system a clip came from. */
export type SourceKind = 
/**  An analog DVR: MJPEG in AVI. */
"analog" | 
/**  A DJI air unit or goggles: H.264 or H.265 in MP4, named by the unit's clock. */
"dji";

/**  `stage` and `load`: a card mount point or a folder. None takes the first detected card. */
export type SourceParams = {
	source: string | null,
	/**
	 *  Join recordings the DVR split into files, this run. None follows the
	 *  `join_split_recordings` setting.
	 */
	join?: boolean | null,
};

/**  A time range in a clip, in seconds: a suggested keep range or a cut. */
export type Span = {
	start: number | null,
	end: number | null,
};

export type Status = Status_Serialize | Status_Deserialize;

export type Status_Deserialize = {
	gui: boolean,
	tools: SerdeResult<Tools, string>,
	defaults: Defaults_Deserialize,
	session: SessionBrief | null,
};

export type Status_Serialize = {
	gui: boolean,
	tools: SerdeResult<Tools, string>,
	defaults: Defaults_Serialize,
	session: SessionBrief | null,
};

/**  `suggest`: changes to clip plans. Without `editor`, an agent made them. */
export type SuggestParams = {
	patches: PlanPatch[],
	editor?: Editor | null,
};

/**  Which fields of a plan an agent wrote and the user has not edited since. */
export type Suggested = {
	date: boolean,
	name: boolean,
	note: boolean,
	skip: boolean,
	cuts?: boolean,
	meta?: boolean,
};

export type Summary = {
	results: ClipResult[],
	imported: number,
	skipped: number,
	failed: number,
	total_bytes: number,
	output_dir: string | null,
	/**  Ok when the format step may unlock, else the reason it stays locked. */
	format_ready: SerdeResult<null, string>,
};

/**
 *  The head's values for the other state of the join: the file's own while the join is on,
 *  the whole recording's while it is off. Turning the join on or off swaps them in.
 */
export type Swap = {
	duration: number | null,
	probe: Probe | null,
	signal: SignalScan | null,
	detail: string,
};

/**  The long library jobs. */
export type Task = "rebuild" | "cuts" | "thumbnails" | "moments";

export type Tools = {
	ffmpeg: string,
	ffprobe: string,
};

/**  Totals for the footer. */
export type Totals = {
	clips: number,
	bytes: number,
	seconds: number | null,
	flying: number | null,
};

export type TrashReport = {
	trashed: string[],
	failed: ([string, string])[],
	/**  Where each file went, so `library_untrash` can put it back. */
	moved: Moved[],
};

export type Tunables = {
	/**  A gap over this many seconds between rows starts a new armed segment. */
	segment_gap_s: number | null,
	/**  A gap over this many minutes between segments starts a new session. */
	session_gap_min: number | null,
	/**  Slack, in seconds, allowed when a clip claims segments. */
	tolerance_s: number | null,
	/**  A log day further than this from the import date means the radio clock reset. */
	max_log_age_days: number,
	/**
	 *  A clip with its own clock (DJI) takes a matching log's time only when the log starts
	 *  within this many seconds of the clip clock.
	 */
	clock_skew_s?: number | null,
};

/**  `library_untrash`: the files `library_trash` moved. */
export type UntrashParams = {
	moved: Moved[],
};

/**  `verify`: the clips to check again (all verified clips when None). */
export type VerifyParams = {
	ids: number[] | null,
};

export type VerifyReport = {
	id: number,
	output: string,
	ok: boolean,
	error: string | null,
};

/**  A mounted volume the app may care about. */
export type Volume = {
	mount: string,
	info: DiskInfo,
	/**  Removable and holds clips of a source QuadCam reads. */
	is_card: boolean,
	/**  The video system of the clips on a card. */
	source?: SourceKind | null,
	/**  Holds `LOGS/` next to `MODELS/` or `RADIO/`: an EdgeTX radio in USB Storage mode. */
	is_radio: boolean,
	warnings: string[],
};

/**  Something mounted or unmounted under /Volumes. */
export type VolumesChanged = null;

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

