// Writes src/theme/palette.css from @catppuccin/palette: every Mocha color as --ctp-<name>
// for dark, every Latte color for light. tokens.css maps them to the app's names.
// `node scripts/gen-palette.mjs --check` fails when the file is out of date.
import { flavors } from "@catppuccin/palette";
import { readFileSync, writeFileSync } from "node:fs";

const out = new URL("../src/theme/palette.css", import.meta.url);
const vars = (f) => flavors[f].colorEntries.map(([name, c]) => `  --ctp-${name}: ${c.hex};`).join("\n");
const css = `/* Generated by scripts/gen-palette.mjs from @catppuccin/palette. Do not edit. */
:root {
${vars("mocha")}
  color-scheme: dark;
}
@media (prefers-color-scheme: light) {
  :root {
${vars("latte").replace(/^/gm, "  ")}
    color-scheme: light;
  }
}
`;
if (process.argv.includes("--check")) {
  if (readFileSync(out, "utf8") !== css) {
    console.error("src/theme/palette.css is out of date: run node scripts/gen-palette.mjs");
    process.exit(1);
  }
} else {
  writeFileSync(out, css);
}
